# Generated by Django 4.0.5 on 2022-07-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_userinformation_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
