# Generated by Django 4.0.6 on 2022-07-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_userinformation_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
