# Generated by Django 4.0.5 on 2022-07-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
